package com.example.reentry.service;

import com.example.reentry.dto.CreateEventRequest;
import com.example.reentry.dto.EventResponse;
import com.example.reentry.model.Event;
import com.example.reentry.repository.EventRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

import java.time.LocalDateTime;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class EventServiceImplTest {

    @InjectMocks
    private EventServiceImpl eventService;

    @Mock
    private EventRepository eventRepository;

    @Test
    void shouldRejectEventWhenEndTimeIsBeforeStartTime() {
        LocalDateTime startTime = LocalDateTime.of(2026, 8, 1, 11, 0);
        LocalDateTime endTime = LocalDateTime.of(2026, 8, 1, 10, 0);
        CreateEventRequest request = new CreateEventRequest(
                "Dentist appointment",
                "Annual checkup",
                startTime,
                endTime);

        assertThrows(IllegalArgumentException.class, () -> eventService.createEvent(request));
    }

    @Test
    void shouldCreateEvent() {

        UUID autoGeneratedEventId = UUID.randomUUID();

        CreateEventRequest request = new CreateEventRequest(
                "Dentist appointment",
                "Annual checkup",
                LocalDateTime.of(2026, 8, 1, 10, 0),
                LocalDateTime.of(2026, 8, 1, 11, 0));


        // Mimics a real repository: returns the same entity it was given, now with an id assigned.
        when(eventRepository.save(any(Event.class))).thenAnswer(invocation -> {
            Event savedEvent = invocation.getArgument(0);
            ReflectionTestUtils.setField(savedEvent,
                    "id",
                    autoGeneratedEventId);
            return savedEvent;
        });

        EventResponse actual = eventService.createEvent(request);

        assertThat(actual)
                .returns(autoGeneratedEventId, EventResponse::id)
                .returns(request.name(), EventResponse::name)
                .returns(request.description(), EventResponse::description)
                .returns(request.startTime(), EventResponse::startTime)
                .returns(request.endTime(), EventResponse::endTime);
    }
}
